### ISSUE TITLE
Use async instead

### ISSUE THREAD

**Issue by riccardone** [benfoster/Ditto#1]
https://github.com/benfoster/Ditto/blob/61717d64f4b951fccddca5ff3afa118a14500694/src/Ditto/ReplicatingConsumer.cs#L44

This code is calling an asynchronous operation and blocking on it synchronously with task.GetAwaiter().GetResult(). It's not asynchronous and may lead to deadlocks.

You should use the async and await keywords all the way up, or you shouldn't use async at all.

**Comment by benfoster** [comment]
@riccardone sorry for my late reply. 

Unless I'm missing something `ConnectToPersistentSubscriptionAsync` accepts an `Action<EventStorePersistentSubscriptionBase, ResolvedEvent>`. If this is made async, can you confirm if it is awaited?

**Comment by benfoster** [comment]
Didn't realise this got added in https://github.com/EventStore/EventStore/pull/1310. Will fix.
